spring:
  application:
    name: library
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true

  datasource:
    url: jdbc:h2:file:${DB_FILE}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect

